service: blueprint-transactions

custom:
  defaultStage: dev
  currentStage: ${opt:stage, self:custom.defaultStage}
  currentRegion: ${file(../../config/config.${self:custom.currentStage}.json):region}

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${self:custom.currentStage}
  region: ${self:custom.currentRegion}
  apiGateway:
    restApiId:
      'Fn::ImportValue': SharedGW-restApiId
    restApiRootResourceId:
      'Fn::ImportValue': SharedGW-rootResourceId
functions:
  get-transactions:
    handler: handler.getTransactions
    events:
      - http:
          path: transactions/list
          method: get
