service: shared-gateway

custom:
  defaultStage: dev
  currentStage: ${opt:stage, self:custom.defaultStage}
  defaultRegion: us-west-2
  currentRegion: ${file(../config/config.${self:custom.currentStage}.json):region, self:custom.defaultRegion}

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${self:custom.currentStage}
  region: ${self:custom.currentRegion}
resources:
  Resources:
    BlueprintGW:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: BlueprintGW
  Outputs:
    apiGatewayRestApiId:
      Value:
        Ref: BlueprintGW
      Export:
        Name: BlueprintGW-${self:custom.currentStage}-restApiId
    apiGatewayRestApiRootResourceId:
      Value:
        Fn::GetAtt:
          - BlueprintGW
          - RootResourceId
      Export:
        Name: BlueprintGW-${self:custom.currentStage}-rootResourceId
