name: deploy

on: [push]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 8.x
        uses: actions/setup-node@v1
        with:
          node-version: 8.x
      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run lint --if-present
          npm run test --if-present
        env:
          CI: true
  deploy:
    name: deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 8.x
        uses: actions/setup-node@v1
        with:
          node-version: 8.x
      - name: Install Serverless
        run: npm i -g serverless
        shell: bash
      - name: Install Lerna
        run: npm i -g lerna
        shell: bash
      - name: Echo Ref
        run: echo ${GITHUB_REF:11}
        shell: bash
      - name: Deploy Branch
        if: github.ref != 'refs/heads/master'
        run: lerna run deploy --scope blueprint-gateway -- --stage ${GITHUB_REF:11} && lerna run deploy --ignore 'blueprint-gateway' -- --stage ${GITHUB_REF:11}
        shell: bash
      - name: Deploy Master
        if: github.ref == 'refs/heads/master'
        run: npm run deploy:prod
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
